library(rgdal)
library(ggplot2)
library(ggmap)
library("plyr")
library(sp)
library(rgeos)
library(maptools)
library(leaflet)
library(dplyr)
library(magrittr)
library(readr)
library(lubridate)
library(RColorBrewer)
library(classInt)
library(raster)
library(gplots)
library(DAAG)

YelpData <- read.csv("/Users/pratikkamath30/Downloads/yelp_final.csv", header = T, sep=",")
YelpDataDF <- as.data.frame(YelpData)
coords <- SpatialPoints(YelpDataDF[,c("longitude","latitude")])
crime_spatial_df <- SpatialPointsDataFrame(coords, YelpDataDF)
proj4string(crime_spatial_df) <-  CRS("+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0")
  
wmap <- readOGR(dsn = "/Users/pratikkamath30/Downloads/Police Precincts/", layer = "geo_export_1a66c59c-5514-4fa5-be7b-81e4cba9dfcb")
plot(wmap, col="grey", axes = TRUE)
plot(crime_spatial_df, col = "SteelBlue", pch = 21, cex = .5,add = TRUE, alpha = 0.05)

wmap_DF <- fortify(wmap)

NYCMap = map = get_map(location = "New York" , zoom = 11, maptype = "terrain")

gg <- ggmap(NYCMap)
gg <- gg + stat_density2d(data=YelpDataDF, aes(x=longitude, y=latitude, fill=..level.., alpha=..level..),
                          geom="polygon", size=0.01, bins=5)
gg <- gg + scale_alpha(range=c(0.2, 0.4), guide=FALSE)
gg <- gg + coord_map()
gg <- gg + facet_wrap(~cut, ncol=3)
gg <- gg + labs(x=NULL, y=NULL, title="Rating Distribution Across NYC Restaurants\n")
gg <- gg + theme(plot.title=element_text(face="bold", hjust=1))
gg <- gg + theme(panel.margin.x=unit(1, "cm"))
gg <- gg + theme(panel.margin.y=unit(1, "cm"))
gg <- gg + theme(legend.position="right")
gg <- gg + theme(strip.background=element_rect(fill="white", color="white"))
gg <- gg + theme(strip.text=element_text(face="bold", hjust=0))
gg

